#ifndef PARAMS_H
#define PARAMS_H

#define CHAINED_ACHILLES
#define MAX_NUM_NODES 3
#define MAX_NUM_SIGNATURES 2
#define MAX_NUM_TEE_SIGNATURES 2
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 256
#define PERSISTENT_COUNTER_TIME 0

#endif
