#ifndef PARAMS_H
#define PARAMS_H

#define BASIC_HYBRID_TEE
#define MAX_NUM_NODES 4
#define MAX_NUM_SIGNATURES 3
#define MAX_NUM_TEE_SIGNATURES 2
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 256
#define PERSISTENT_COUNTER_TIME 0

#endif
