#ifndef PARAMS_H
#define PARAMS_H

#define CHAINED_HYBRID_TEE
#define MAX_NUM_NODES 65
#define MAX_NUM_SIGNATURES 33
#define MAX_NUM_TEE_SIGNATURES 33
#define MAX_NUM_TRANSACTIONS 400
#define PAYLOAD_SIZE 256
#define PERSISTENT_COUNTER_TIME 0

#endif
